Doc strings
upb-lea/materialdatabase pull request #10
Opened 2024-04-18 16:29 UTC by sschachten

- added missing docstrings for functions, classes and scripts

- updated some scripts to the new line length of 160 characters

- added some additional enumerations

2024-04-19 09:11 UTC, gituser789 requested changes

2024-04-19 09:11 UTC, gituser789 commented on materialdatabase/material_data_base_classes.py
> +        @param flux_density_list: [flux1, flux2,..]
must be :param 
@param is another style guide, but we are using :param

2024-04-19 09:11 UTC, gituser789 commented on materialdatabase/material_data_base_classes.py
> +        @param flux_density_list: [flux1, flux2, ....]
:param

2024-04-19 09:11 UTC, gituser789 commented on materialdatabase/material_data_base_classes.py
> -            @type temperature_list: [temp1, temp2, ...]
:param

2024-04-22 08:02 UTC, sschachten commented on materialdatabase/material_data_base_classes.py
> +        @param flux_density_list: [flux1, flux2, ....]
Changed

2024-04-22 08:11 UTC, gituser789 approved these changes

2024-04-22 08:11 UTC, merged